version: '2'

services:
  synch-service:
    container_name: synch-service
    restart: always
    image: liumapp/synchronizing-doc-convert-results:v1.0.0
    ports:
      - 2020:2020
    networks:
      - synchronizing-doc-convert-results

  synch-rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: synch-rabbitmq
    hostname: synch-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "springcloud"
      RABBITMQ_DEFAULT_PASS: "123456"
    ports:
      - "5672:5672"
      - "15672:15672" 
    networks:
      - synchronizing-doc-convert-results

networks:
  synchronizing-doc-convert-results:
    driver: bridge
