server:
    port: 2020

spring:
  profiles:
    active: docker
  thymeleaf:
    suffix: .html
    mode: LEGACYHTML5
#      mode: HTML5
    encoding: UTF-8
    content-type: text/html; charset=utf-8
    cache: false

---
# docker环境
spring:
  profiles: docker
  application:
    name: synch-service
  rabbitmq:
    port: 5672
    host: synch-rabbitmq
    username: springcloud
    password: 123456
liumapp:
  filemanager:
    savePath: /synchronizing-doc-convert-results/data/


---
# idea测试环境
spring:
  profiles: dev
  application:
    name: synch-service
  rabbitmq:
    port: 5672
    host: localhost
    username: springcloud
    password: 123456
liumapp:
  filemanager:
    savePath: /usr/local/tomcat/project/synchronizing-doc-convert-results/data/

