server:
    port: 2020

spring:
    application:
      name: synch-service
    rabbitmq:
      port: 5672
      host: localhost
      username: springcloud
      password: 123456

liumapp:
  filemanager:
    savePath: /usr/local/tomcat/project/synchronizing-doc-convert-results/data/

