server:
    port: 2020

spring:
    application:
      name: synch-service
    rabbitmq:
      port: 5672
      host: synch-rabbitmq
      username: springcloud
      password: 123456

liumapp:
  filemanager:
    savePath: /synchronizing-doc-convert-results/data/

